[book]
authors = ["Claudio Capobianco"]
language = "it"
multilingual = false
src = "src"
title = "TPSI - Quarto anno - 2021"
description = "Materiale di supporto alle lezioni."

[build]
build-dir = "docs"
create-missing = false

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/wbigger/book-tpsi-4y-2021.git"